"""added team record and team game stats

Revision ID: 36b4fdd64607
Revises: 7d2421c9baaf
Create Date: 2026-02-27 22:34:02.892584

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "36b4fdd64607"
down_revision: Union[str, Sequence[str], None] = "7d2421c9baaf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.add_column(
        "scheduled_games",
        sa.Column(
            "id_new",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
    )
    op.drop_constraint("scheduled_games_pkey", "scheduled_games", type_="primary")
    op.drop_column("scheduled_games", "id")
    op.alter_column("scheduled_games", "id_new", new_column_name="id")
    op.create_primary_key("scheduled_games_pkey", "scheduled_games", ["id"])
    op.create_table(
        "team_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("wins", sa.Integer(), nullable=False),
        sa.Column("losses", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_team_records_team_id"), "team_records", ["team_id"], unique=False
    )
    op.create_table(
        "team_game_stats",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.UUID(), nullable=False),
        sa.Column("season_year", sa.Integer(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("fg_attempted", sa.Integer(), nullable=False),
        sa.Column("fg_made", sa.Integer(), nullable=False),
        sa.Column("three_point_attempted", sa.Integer(), nullable=False),
        sa.Column("three_point_made", sa.Integer(), nullable=False),
        sa.Column("ft_attempted", sa.Integer(), nullable=False),
        sa.Column("ft_made", sa.Integer(), nullable=False),
        sa.Column("off_rebounds", sa.Integer(), nullable=False),
        sa.Column("def_rebounds", sa.Integer(), nullable=False),
        sa.Column("rebounds", sa.Integer(), nullable=False),
        sa.Column("assists", sa.Integer(), nullable=False),
        sa.Column("turnovers", sa.Integer(), nullable=False),
        sa.Column("steals", sa.Integer(), nullable=False),
        sa.Column("blocks", sa.Integer(), nullable=False),
        sa.Column("personal_fouls", sa.Integer(), nullable=False),
        sa.Column("technical_fouls", sa.Integer(), nullable=False),
        sa.Column("plus_minus", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["scheduled_games.id"],
            name="fk_team_game_stats_game_id_scheduled_games",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_team_game_stats_game_id"), "team_game_stats", ["game_id"], unique=False
    )
    op.create_index(
        op.f("ix_team_game_stats_team_id"), "team_game_stats", ["team_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_team_game_stats_team_id"), table_name="team_game_stats")
    op.drop_index(op.f("ix_team_game_stats_game_id"), table_name="team_game_stats")
    op.drop_table("team_game_stats")
    op.drop_index(op.f("ix_team_records_team_id"), table_name="team_records")
    op.drop_table("team_records")
    op.add_column(
        "scheduled_games",
        sa.Column("id_int", sa.Integer(), autoincrement=True, nullable=True),
    )
    op.execute("UPDATE scheduled_games SET id_int = nextval('scheduled_games_id_seq')")
    op.drop_constraint("scheduled_games_pkey", "scheduled_games", type_="primary")
    op.drop_column("scheduled_games", "id")
    op.alter_column("scheduled_games", "id_int", new_column_name="id")
    op.create_primary_key("scheduled_games_pkey", "scheduled_games", ["id"])
    # ### end Alembic commands ###
