"""added year to team record

Revision ID: 4c9f0c5ed4db
Revises: 36b4fdd64607
Create Date: 2026-02-27 22:46:32.142636

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4c9f0c5ed4db"
down_revision: Union[str, Sequence[str], None] = "36b4fdd64607"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("team_records", sa.Column("year", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("team_records", "year")
    # ### end Alembic commands ###
