"""added scheduled games

Revision ID: 7d2421c9baaf
Revises: d65ef04c1bf9
Create Date: 2026-02-25 21:04:09.646555

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7d2421c9baaf"
down_revision: Union[str, Sequence[str], None] = "d65ef04c1bf9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scheduled_games",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("season_year", sa.Integer(), nullable=False),
        sa.Column("game_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("home_team_id", sa.Integer(), nullable=False),
        sa.Column("away_team_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scheduled_games_away_team_id"),
        "scheduled_games",
        ["away_team_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_games_home_team_id"),
        "scheduled_games",
        ["home_team_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_scheduled_games_home_team_id"), table_name="scheduled_games")
    op.drop_index(op.f("ix_scheduled_games_away_team_id"), table_name="scheduled_games")
    op.drop_table("scheduled_games")
    # ### end Alembic commands ###
