"""Added player characters and users tables

Revision ID: ca47d40b3aab
Revises: 4c9f0c5ed4db
Create Date: 2026-05-31 16:40:48.621465

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ca47d40b3aab"
down_revision: Union[str, Sequence[str], None] = "4c9f0c5ed4db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("primary_platform", sa.String(), nullable=True),
        sa.Column("last_login_platform", sa.String(), nullable=True),
        sa.Column("user_device_id", sa.String(), nullable=True),
        sa.Column("steam_id", sa.String(), nullable=True),
        sa.Column("steam_username", sa.String(), nullable=True),
        sa.Column("xbox_id", sa.String(), nullable=True),
        sa.Column("xbox_gamertag", sa.String(), nullable=True),
        sa.Column("psn_id", sa.String(), nullable=True),
        sa.Column("psn_username", sa.String(), nullable=True),
        sa.Column("epic_id", sa.String(), nullable=True),
        sa.Column("epic_username", sa.String(), nullable=True),
        sa.Column("nintendo_id", sa.String(), nullable=True),
        sa.Column("nintendo_username", sa.String(), nullable=True),
        sa.Column("preferred_locale", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("epic_id"),
        sa.UniqueConstraint("nintendo_id"),
        sa.UniqueConstraint("psn_id"),
        sa.UniqueConstraint("steam_id"),
        sa.UniqueConstraint("user_device_id"),
        sa.UniqueConstraint("xbox_id"),
    )
    op.create_table(
        "player_characters",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("play_style", sa.String(), nullable=True),
        sa.Column("reputation", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.CheckConstraint(
            "reputation >= 0 AND reputation <= 100",
            name="ck_player_characters_reputation_range",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_player_characters_team_id"),
        "player_characters",
        ["team_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_player_characters_user_id"),
        "player_characters",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_player_characters_user_id"), table_name="player_characters")
    op.drop_index(op.f("ix_player_characters_team_id"), table_name="player_characters")
    op.drop_table("player_characters")
    op.drop_table("users")
    # ### end Alembic commands ###
