"""updated player game stats

Revision ID: d29899737dc1
Revises: e611a6a0426a
Create Date: 2026-02-21 18:54:51.852366

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d29899737dc1"
down_revision: Union[str, Sequence[str], None] = "e611a6a0426a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_game_stats",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("fg_attempted", sa.Integer(), nullable=False),
        sa.Column("fg_made", sa.Integer(), nullable=False),
        sa.Column("fg_percent", sa.Float(), nullable=False),
        sa.Column("three_point_attempted", sa.Integer(), nullable=False),
        sa.Column("three_point_made", sa.Integer(), nullable=False),
        sa.Column("three_point_percent", sa.Float(), nullable=False),
        sa.Column("ft_attempted", sa.Integer(), nullable=False),
        sa.Column("ft_made", sa.Integer(), nullable=False),
        sa.Column("ft_percent", sa.Float(), nullable=False),
        sa.Column("off_rebounds", sa.Integer(), nullable=False),
        sa.Column("def_rebounds", sa.Integer(), nullable=False),
        sa.Column("rebounds", sa.Integer(), nullable=False),
        sa.Column("assists", sa.Integer(), nullable=False),
        sa.Column("turnovers", sa.Integer(), nullable=False),
        sa.Column("steals", sa.Integer(), nullable=False),
        sa.Column("blocks", sa.Integer(), nullable=False),
        sa.Column("personal_fouls", sa.Integer(), nullable=False),
        sa.Column("technical_fouls", sa.Integer(), nullable=False),
        sa.Column("plus_minus", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_player_game_stats_player_id"),
        "player_game_stats",
        ["player_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_game_stats_player_id"), table_name="game_stats")
    op.drop_table("game_stats")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_stats",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("player_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("minutes", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("points", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("fg_attempted", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("fg_made", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "three_point_attempted", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "three_point_made", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("ft_attempted", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("ft_made", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "fg_percent",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "three_point_percent",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("off_rebounds", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("def_rebounds", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("rebounds", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("assists", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("turnovers", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("steals", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("blocks", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("personal_fouls", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("technical_fouls", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("plus_minus", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("game_stats_player_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("game_stats_pkey")),
    )
    op.create_index(
        op.f("ix_game_stats_player_id"), "game_stats", ["player_id"], unique=False
    )
    op.drop_index(
        op.f("ix_player_game_stats_player_id"), table_name="player_game_stats"
    )
    op.drop_table("player_game_stats")
    # ### end Alembic commands ###
