"""added conferences and divisions

Revision ID: d65ef04c1bf9
Revises: d29899737dc1
Create Date: 2026-02-22 09:34:52.192794

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d65ef04c1bf9"
down_revision: Union[str, Sequence[str], None] = "d29899737dc1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conferences",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("league_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["league_id"],
            ["leagues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conferences_league_id"), "conferences", ["league_id"], unique=False
    )
    op.create_table(
        "divisions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("conference_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conference_id"],
            ["conferences.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_divisions_conference_id"), "divisions", ["conference_id"], unique=False
    )
    op.add_column("teams", sa.Column("division_id", sa.Integer(), nullable=False))
    op.drop_index(op.f("ix_teams_league_id"), table_name="teams")
    op.create_index(
        op.f("ix_teams_division_id"), "teams", ["division_id"], unique=False
    )
    op.drop_constraint(op.f("teams_league_id_fkey"), "teams", type_="foreignkey")
    op.create_foreign_key(
        "fk_teams_division_id_divisions",
        "teams",
        "divisions",
        ["division_id"],
        ["id"],
    )
    op.drop_column("teams", "league_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teams",
        sa.Column("league_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint("fk_teams_division_id_divisions", "teams", type_="foreignkey")
    op.create_foreign_key(
        op.f("teams_league_id_fkey"), "teams", "leagues", ["league_id"], ["id"]
    )
    op.drop_index(op.f("ix_teams_division_id"), table_name="teams")
    op.create_index(op.f("ix_teams_league_id"), "teams", ["league_id"], unique=False)
    op.drop_column("teams", "division_id")
    op.drop_index(op.f("ix_divisions_conference_id"), table_name="divisions")
    op.drop_table("divisions")
    op.drop_index(op.f("ix_conferences_league_id"), table_name="conferences")
    op.drop_table("conferences")
    # ### end Alembic commands ###
