"""player and game stats tables

Revision ID: e24d5f6ec160
Revises: 9774c3f23d9b
Create Date: 2026-02-15 16:43:20.392288

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e24d5f6ec160"
down_revision: Union[str, Sequence[str], None] = "9774c3f23d9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "players",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("archetype", sa.String(), nullable=False),
        sa.Column("positions", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_players_team_id"), "players", ["team_id"], unique=False)
    op.create_table(
        "game_stats",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("minutes", sa.Integer(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("fg_attempted", sa.Integer(), nullable=False),
        sa.Column("fg_made", sa.Integer(), nullable=False),
        sa.Column("three_point_attempted", sa.Integer(), nullable=False),
        sa.Column("three_point_made", sa.Integer(), nullable=False),
        sa.Column("ft_attempted", sa.Integer(), nullable=False),
        sa.Column("ft_made", sa.Integer(), nullable=False),
        sa.Column("fg_percent", sa.Float(), nullable=False),
        sa.Column("three_point_percent", sa.Float(), nullable=False),
        sa.Column("off_rebounds", sa.Integer(), nullable=False),
        sa.Column("def_rebounds", sa.Integer(), nullable=False),
        sa.Column("rebounds", sa.Integer(), nullable=False),
        sa.Column("assists", sa.Integer(), nullable=False),
        sa.Column("turnovers", sa.Integer(), nullable=False),
        sa.Column("steals", sa.Integer(), nullable=False),
        sa.Column("blocks", sa.Integer(), nullable=False),
        sa.Column("personal_fouls", sa.Integer(), nullable=False),
        sa.Column("technical_fouls", sa.Integer(), nullable=False),
        sa.Column("plus_minus", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_game_stats_player_id"), "game_stats", ["player_id"], unique=False
    )
    op.create_table(
        "player_attributes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("speed", sa.Integer(), nullable=False),
        sa.Column("agility", sa.Integer(), nullable=False),
        sa.Column("strength", sa.Integer(), nullable=False),
        sa.Column("stamina", sa.Integer(), nullable=False),
        sa.Column("inside_scoring", sa.Integer(), nullable=False),
        sa.Column("midrange_scoring", sa.Integer(), nullable=False),
        sa.Column("free_throw", sa.Integer(), nullable=False),
        sa.Column("three_point", sa.Integer(), nullable=False),
        sa.Column("ball_handling", sa.Integer(), nullable=False),
        sa.Column("passing", sa.Integer(), nullable=False),
        sa.Column("off_ball_movement", sa.Integer(), nullable=False),
        sa.Column("perimeter_defense", sa.Integer(), nullable=False),
        sa.Column("interior_defense", sa.Integer(), nullable=False),
        sa.Column("steal", sa.Integer(), nullable=False),
        sa.Column("block", sa.Integer(), nullable=False),
        sa.Column("def_rebound", sa.Integer(), nullable=False),
        sa.Column("off_rebound", sa.Integer(), nullable=False),
        sa.Column("iq", sa.Integer(), nullable=False),
        sa.Column("clutch", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_player_attributes_player_id"),
        "player_attributes",
        ["player_id"],
        unique=False,
    )
    op.create_index(op.f("ix_teams_league_id"), "teams", ["league_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_teams_league_id"), table_name="teams")
    op.drop_index(
        op.f("ix_player_attributes_player_id"), table_name="player_attributes"
    )
    op.drop_table("player_attributes")
    op.drop_index(op.f("ix_game_stats_player_id"), table_name="game_stats")
    op.drop_table("game_stats")
    op.drop_index(op.f("ix_players_team_id"), table_name="players")
    op.drop_table("players")
    # ### end Alembic commands ###
