"""player db schema updates

Revision ID: e611a6a0426a
Revises: e24d5f6ec160
Create Date: 2026-02-15 18:19:53.024854

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e611a6a0426a"
down_revision: Union[str, Sequence[str], None] = "e24d5f6ec160"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("player_attributes", "off_ball_movement")
    op.add_column("players", sa.Column("height", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "height")
    op.add_column(
        "player_attributes",
        sa.Column(
            "off_ball_movement", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
