name: Lint and Format Check

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch full history for linters

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff Linter and Formatter Check
        run: |
          # The --check flag makes the command fail if issues are found
          ruff check .
          ruff format . --check --diff
